// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import os from "node:os";
import path from "node:path";
import { defineConfig } from "prisma/config";

const persistentDir = process.env["PERCENT_HOME"] ?? path.join(os.homedir(), ".percent-tracker");
const databasePath = process.env["PERCENT_DATABASE_PATH"] ?? path.join(persistentDir, "percent.db");

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: `file:${databasePath}`,
  },
});
